# Generated by Django 5.0.6 on 2024-05-31 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=10000)),
                ('author', models.CharField(max_length=100)),
                ('time', models.DateTimeField(default=datetime.datetime(2024, 5, 31, 14, 20, 58, 9273, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
