# Generated by Django 5.0.6 on 2024-05-31 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 56, 52, 634314, tzinfo=datetime.timezone.utc)),
        ),
    ]
