# Generated by Django 5.0.6 on 2024-05-31 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogcontent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 18, 28, 28, 566159, tzinfo=datetime.timezone.utc)),
        ),
    ]
