# Generated by Django 5.0.6 on 2024-06-01 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogcontent_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='blog_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
