# Generated by Django 5.0.6 on 2024-06-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogcontent_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='thumbnail',
            field=models.ImageField(upload_to='blog'),
        ),
    ]
