# Generated by Django 5.0.6 on 2024-06-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogcontent_comment_blogcontent_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontent',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='blogcontent',
            name='like',
        ),
        migrations.RemoveField(
            model_name='blogcontent',
            name='report',
        ),
    ]
